# Generated by Django 4.1.3 on 2022-12-02 09:03

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('health_data', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('address', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
            ],
        ),
    ]
